title: CASCaRA Homepage
description: Homepage with goals, organization and results of the CASCaRA Project.
theme: just-the-docs

url: https://cascara.gfse.org
heading_anchors: true

aux_links:
  Repo: https://github.com/GfSE/CASCaDE-Pages
